### ISSUE TITLE
Any help?

### ISSUE THREAD

**Issue by nw** [WebDevBootcamp/hatsallfolks#10]
Happy to help with branch management. Let me know if you want some help with consolidating your efforts.

@BradAyers every all right? I haven't seen a commit from you.

**Comment by BradAyers** [comment]
Nate,

I have been emailing URL's to the code that I uploaded to my directory at
http://weblab.us/ba/hatsall/ to my team members. Lot's of extraneous BS
going on right now that seriously cuts in to my time to work on figuring
out more on Git.   What's the best way to connect with you on how to upload
this stuff to my git branch?  Thanks in advance for any assistance you can
give me.

On Fri, May 15, 2015 at 5:03 PM, Nathan White notifications@github.com
wrote:

> Happy to help with branch management. Let me know if you want some help
> with consolidating your efforts.
> 
> @BradAyers https://github.com/BradAyers every all right? I haven't seen
> a commit from you.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WebDevBootcamp/hatsallfolks/issues/10.

## 

Brad Ayers
303-588-6397 cell
Brad@AyersKin.com

**Comment by nw** [comment]
It's all good.  I actually don't want you to worry about git too much.

What I am noticing is a discrepancy with your team and the others. Your
team is tackling a lot more complexity with your backend implementation. I
have noticed what is on the server and in the repo doesn't jive. Again,
this is ok. I'm here to help if you want. All I'm trying to do is make sure
that code isn't accidentally lost as you make more changes as the deadline
encroaches.

If you get a chance you might want to start from a fresh clone.

In the command line (I think you want to go that direction right?) type the
following

``` bash
git branch brad-latest
git checkout brad-latest
```

try syncing anything you may have. Commit any changes and then:

``` bash
git push origin brad-latest
```

From there I maybe able to help sort out your code and help resolve any
conflicts so everyone is in sync.

BTW, I think you guys are doing great! So please don't take this the wrong
way.

Just trying to help.

**Comment by BradAyers** [comment]
Good morning Nate,

Thanks for your help.  I really appreciate you as an instructor (not trying
to gain any brownie points, but you have been my favorite instructor during
WebLab).  I entered this in the terminal:
[image: Inline image 1]
and nothing happened.  I will try a fresh clone and enter the instructions
again.Until I get this working on my branch I had considered making a new
repo on my git and uploading my code there in the meantime.  I know that is
not the best solution, since that will require copy and paste and won't
facilitate merging, but I figured that may make my code more transparent.
In retrospect I'm thinking it may have been better if I had just focused on
using Sourcetree and saved learning the terminal for later.  Oh well, I've
become very comfortable with git init, add, status, commit, push and pull.
I'm sure someday soon I'll get it all figured out and be the guy that's
helping out another newbie to git figure out how to use it. Thank you again
for being a great example of the type of developer I plan on being when
I've gained more experience as a web developer.

On Sat, May 16, 2015 at 5:42 AM, Nathan White notifications@github.com
wrote:

> It's all good. I actually don't want you to worry about git too much.
> 
> What I am noticing is a discrepancy with your team and the others. Your
> team is tackling a lot more complexity with your backend implementation. I
> have noticed what is on the server and in the repo doesn't jive. Again,
> this is ok. I'm here to help if you want. All I'm trying to do is make sure
> that code isn't accidentally lost as you make more changes as the deadline
> encroaches.
> 
> If you get a chance you might want to start from a fresh clone.
> 
> In the command line (I think you want to go that direction right?) type the
> following
> 
> ``` bash
> git branch brad-latest
> git checkout brad-latest
> ```
> 
> try syncing anything you may have. Commit any changes and then:
> 
> ``` bash
> git push origin brad-latest
> ```
> 
> From there I maybe able to help sort out your code and help resolve any
> conflicts so everyone is in sync.
> 
> BTW, I think you guys are doing great! So please don't take this the wrong
> way.
> 
> Just trying to help.
> 
> On May 15, 2015, at 11:48 PM, Brad Ayers notifications@github.com wrote:
> 
> Nate,
> 
> I have been emailing URL's to the code that I uploaded to my directory at
> http://weblab.us/ba/hatsall/ to my team members. Lot's of extraneous BS
> going on right now that seriously cuts in to my time to work on figuring
> out more on Git. What's the best way to connect with you on how to upload
> this stuff to my git branch? Thanks in advance for any assistance you can
> give me.
> 
> On Fri, May 15, 2015 at 5:03 PM, Nathan White notifications@github.com
> wrote:
> 
> > Happy to help with branch management. Let me know if you want some help
> > with consolidating your efforts.
> > 
> > @BradAyers https://github.com/BradAyers every all right? I haven't
> > seen
> > a commit from you.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/WebDevBootcamp/hatsallfolks/issues/10.
> 
> ## 
> 
> Brad Ayers
> 303-588-6397 cell
> Brad@AyersKin.com
> 
> —
> Reply to this email directly or view it on GitHub
> <
> https://github.com/WebDevBootcamp/hatsallfolks/issues/10#issuecomment-102573159
> 
> 
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WebDevBootcamp/hatsallfolks/issues/10#issuecomment-102614707
> .

## 

Brad Ayers
303-588-6397 cell
Brad@AyersKin.com

**Comment by nw** [comment]
If a new repo works thats fine. I just encourage you to get it committed. 

Git is HARD. Version control is hard. It doesn't stick over night. It took me a while too, and there are still many parts I feel uncomfortable with because I don't use it often.

I'll be in the classroom on Monday. Everything is good. I know your working hard.

If you want we could do a google hangout this weekend as well. You let me know what time works for you.

**Comment by BradAyers** [comment]
Hey Nate,

I just had a telephone meeting with Jack on our code and he confirmed that
my branch is updated.  Funny thing, since my antiquated computer was still
showing my github.com branch with nothing other than the README.md file on
it.  The first paycheck I get from my new web dev career is going to spent
on a new computer (LOL).

Thanks for the reassurance about Git  I guess it will be an ongoing
learning curve.  The google hangout sounds great.  I've got a lot of stuff
going on this weekend, but I could make it a priority if you think it would
be helpful.  Otherwise, I can just look forward to catching up with you on
Monday.  Let me know if you think it would be best to touch bases over
google this weekend and we can set up a time.  Otherwise, I'll see you
Monday.  Thanks again for everything.

I'm off to meet the client that I just built the website for to collect
payment.  I look forward to doing a whole lot more of web dev in the
future.  Take care.

On Sat, May 16, 2015 at 9:16 AM, Nathan White notifications@github.com
wrote:

> If a new repo works thats fine. I just encourage you to get it committed.
> 
> Git is HARD. Version control is hard. It doesn't stick over night. It took
> me a while too, and there are still many parts I feel uncomfortable with
> because I don't use it often.
> 
> I'll be in the classroom on Monday. Everything is good. I know your
> working hard.
> 
> If you want we could do a google hangout this weekend as well. You let me
> know what time works for you.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WebDevBootcamp/hatsallfolks/issues/10#issuecomment-102636338
> .

## 

Brad Ayers
303-588-6397 cell
Brad@AyersKin.com

**Comment by JWLeRoi** [comment]
It looks like Brad has GitHub working now. There's a branch named "Brad" that's empty and one named "brad" that has Brad's files in it. I'm going to open an issue on deleting the empty branch.

**Comment by JWLeRoi** [comment]
Project prototype was presented successfully at graduation
