### ISSUE TITLE
Link not Functioning

### ISSUE THREAD

**Issue by mikeyoutz** [WebDevBootcamp/hatsallfolks#13]
Woops!
Just realized that I have a link that is not working on the thumbnail section. I have covered it up with an inset drop shadow so it's not responding to the mouse. I will redo it and repost in the next few hours. Sorry, trying to be too clever can bite a person in the butt sometimes.

**Comment by JWLeRoi** [comment]
Okay! Well, I just ran into that. Let me know when its working so I can set up the event listeners to open the detail pages. Meanwhile, take a look at http://weblab.us/hatsall/start for the way it looks so far. If you have thumbnail pictures for the hats, we can put them up on the server so we can use them with the templates.

**Comment by JWLeRoi** [comment]
I duplicate that link and added it to the white space below the thumbnail so I could work with it while you're taking care of the real one. I noticed that only part of the text is live. It seems a little confusing to use.

It's like this:
<div class="thumb-text-float-right">> Click Here for <a class=detail-link id="<%= el.sku%>" href="#Brixton-Detail">More Information</a>

It might be better like this:
<div class="thumb-text-float-right"><a class=detail-link id="<%= el.sku%>" href="#Brixton-Detail">> Click Here for More Information</a>

**Comment by JWLeRoi** [comment]
Oh, that didn't work because it read it as HTML and not text. I'll put it in with HTML comments. 

It's like this:
<?--div class="thumb-text-float-right"-->> Click Here for <?--a class=detail-link id="<%= el.sku%> href="#Brixton-Detail"-->More Information<?--/a-->

It might be better like this:
<?--div class="thumb-text-float-right"--><?--a class=detail-link id="<%= el.sku%> href="#Brixton-Detail"-->> Click Here for More Information<?--/a-->

**Comment by JWLeRoi** [comment]
Fixed the link today when I updated the start page to the current design.
